[package]
name = "rslogo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.9.3"
clap = { version = "4.4.4", features = ["derive"] }
logos = "0.14.0"
regex = "1.10.3"
unsvg = "1.1.1"
